/**
 * country-map.js — DIBANGUN OTOMATIS oleh scripts/build_country_map.py.
 * JANGAN diedit manual; jalankan ulang skrip untuk memperbarui.
 *
 * Sumber: ESPN (leagues/<slug>/countries + /teams). Klub memakai
 * prefix slug ('esp.real_madrid' -> Spanyol); timnas memakai kode
 * 3 huruf ('fij' -> Fiji). Nama negara sudah dalam Bahasa Indonesia.
 *
 * 660 entri (660 klub + timnas).
 */

export const TEAM_COUNTRY = {
  "1. FC Union Berlin": "Jerman",
  "2 de Mayo": "Paraguay",
  "AC Milan": "Italia",
  "ADO Den Haag": "Belanda",
  "AEK Athens": "Yunani",
  "AFC '34": "Belanda",
  "AFC Bournemouth": "Inggris",
  "AGF": "Denmark",
  "AJ Auxerre": "Prancis",
  "AS Monaco": "Prancis",
  "AS Roma": "Italia",
  "AZ Alkmaar": "Belanda",
  "Aberdeen": "Skotlandia",
  "Accrington Stanley": "Inggris",
  "Adelaide United": "Australia",
  "Afghanistan": "Afghanistan",
  "Ajax Amateurs": "Belanda",
  "Ajax Amsterdam": "Belanda",
  "Alavés": "Spanyol",
  "Albacete": "Spanyol",
  "Albania": "Albania",
  "Algeria": "Aljazair",
  "Alianza Atlético": "Peru",
  "Almere City": "Belanda",
  "Almería": "Spanyol",
  "American Samoa": "American Samoa",
  "América": "Meksiko",
  "América de Cali": "Kolombia",
  "Anderlecht": "Belgia",
  "Andorra": "Andorra",
  "Angers": "Prancis",
  "Angola": "Angola",
  "Anguilla": "Anguilla",
  "Antigua and Barbuda": "Antigua and Barbuda",
  "Argentina": "Argentina",
  "Argentinos Juniors": "Argentina",
  "Arouca": "Portugal",
  "Arsenal": "Inggris",
  "Aruba": "Aruba",
  "Aston Villa": "Inggris",
  "Atalanta": "Italia",
  "Athletic Club": "Spanyol",
  "Athletico-PR": "Brasil",
  "Atlanta United FC": "Amerika Serikat",
  "Atlante": "Meksiko",
  "Atlas": "Meksiko",
  "Atlético Junior": "Kolombia",
  "Atlético Madrid": "Spanyol",
  "Atlético Nacional": "Kolombia",
  "Atlético de San Luis": "Meksiko",
  "Atlético-MG": "Brasil",
  "Audax Italiano": "Chili",
  "Australia": "Australia",
  "Austria": "Austria",
  "Austria Vienna": "Austria",
  "Avispa Fukuoka": "Jepang",
  "Azerbaijan": "Azerbaijan",
  "Bahamas": "Bahamas",
  "Bahia": "Brasil",
  "Bahrain": "Bahrain",
  "Bangladesh": "Bangladesh",
  "Barbados": "Barbados",
  "Barcelona": "Spanyol",
  "Barcelona SC": "Ekuador",
  "Barnet": "Inggris",
  "Barnsley": "Inggris",
  "Barracas Central": "Argentina",
  "Bayer Leverkusen": "Jerman",
  "Bayern Munich": "Jerman",
  "Belarus": "Belarus",
  "Belgium": "Belgia",
  "Belize": "Belize",
  "Benfica": "Portugal",
  "Benin": "Benin",
  "Bennekom": "Belanda",
  "Bermuda": "Bermuda",
  "Besiktas": "Turki",
  "Birmingham City": "Inggris",
  "Blackburn Rovers": "Inggris",
  "Blackpool": "Inggris",
  "Blooming": "Bolivia",
  "Boca Juniors": "Argentina",
  "Bolivia": "Bolivia",
  "Bologna": "Italia",
  "Bolton Wanderers": "Inggris",
  "Bolívar": "Bolivia",
  "Bonaire": "Bonaire",
  "Borussia Dortmund": "Jerman",
  "Borussia Mönchengladbach": "Jerman",
  "Bosnia-Herzegovina": "Bosnia-Herzegovina",
  "Boston River": "Uruguay",
  "Botafogo": "Brasil",
  "Botswana": "Botswana",
  "Bradford City": "Inggris",
  "Braga": "Portugal",
  "Brazil": "Brasil",
  "Brentford": "Inggris",
  "Brest": "Prancis",
  "Brighton & Hove Albion": "Inggris",
  "Brisbane Roar": "Australia",
  "Bristol City": "Inggris",
  "Bristol Rovers": "Inggris",
  "British Virgin Islands": "British Virgin Islands",
  "Bulgaria": "Bulgaria",
  "Burgos": "Spanyol",
  "Burkina Faso": "Burkina Faso",
  "Burnley": "Inggris",
  "Burton Albion": "Inggris",
  "Burundi": "Burundi",
  "C.D. Nacional": "Portugal",
  "CD Sabadell": "Spanyol",
  "CF Montréal": "Amerika Serikat",
  "Cagliari": "Italia",
  "Cambodia": "Cambodia",
  "Cambridge United": "Inggris",
  "Cameroon": "Kamerun",
  "Canada": "Kanada",
  "Cape Verde": "Cape Verde Islands",
  "Carabobo": "Venezuela",
  "Caracas FC": "Venezuela",
  "Cardiff City": "Inggris",
  "Castellón": "Spanyol",
  "Caykur Rizespor": "Turki",
  "Cayman Islands": "Cayman Islands",
  "Celta Vigo": "Spanyol",
  "Celtic": "Skotlandia",
  "Central Coast Mariners": "Australia",
  "Cercle Brugge KSV": "Belgia",
  "Cerezo Osaka": "Jepang",
  "Cerro Porteño": "Paraguay",
  "Charlton Athletic": "Inggris",
  "Chelsea": "Inggris",
  "Cheltenham Town": "Inggris",
  "Chesterfield": "Inggris",
  "Chicago Fire FC": "Amerika Serikat",
  "Chile": "Chili",
  "China": "China",
  "Club Brugge": "Belgia",
  "Club Olimpia": "Paraguay",
  "Cobresal": "Chili",
  "Colchester United": "Inggris",
  "Colombia": "Kolombia",
  "Colorado Rapids": "Amerika Serikat",
  "Columbus Crew": "Amerika Serikat",
  "Como": "Italia",
  "Comoros": "Comoros Islands",
  "Congo DR": "Kongo DR",
  "Cook Islands": "Cook Islands",
  "Coquimbo Unido": "Chili",
  "Corinthians": "Brasil",
  "Coritiba": "Brasil",
  "Costa Rica": "Kosta Rika",
  "Coventry City": "Inggris",
  "Crawley Town": "Inggris",
  "Crewe Alexandra": "Inggris",
  "Croatia": "Kroasia",
  "Cruz Azul": "Meksiko",
  "Cruzeiro": "Brasil",
  "Crystal Palace": "Inggris",
  "Cuba": "Kuba",
  "Cusco FC": "Peru",
  "Cyprus": "Siprus",
  "Czechia": "Ceko",
  "Cádiz": "Spanyol",
  "Córdoba": "Spanyol",
  "D.C. United": "Amerika Serikat",
  "DOVO": "Belanda",
  "DVS '33 Ermelo": "Belanda",
  "De Graafschap": "Belanda",
  "De Treffers": "Belanda",
  "Defensor Sporting": "Uruguay",
  "Denmark": "Denmark",
  "Deportes Tolima": "Kolombia",
  "Deportivo": "Spanyol",
  "Deportivo Cuenca": "Ekuador",
  "Deportivo Táchira": "Venezuela",
  "Derby County": "Inggris",
  "Dinamo Zagreb": "Kroasia",
  "Djibouti": "Djibouti",
  "Dominica": "Dominica",
  "Dominican Republic": "Republik Dominika",
  "Doncaster Rovers": "Inggris",
  "Dongen": "Belanda",
  "Dundee": "Skotlandia",
  "Dundee United": "Skotlandia",
  "Dynamo Kyiv": "Rusia",
  "EVV Echt": "Belanda",
  "Ecuador": "Ekuador",
  "Egypt": "Mesir",
  "Eibar": "Spanyol",
  "Eintracht Frankfurt": "Jerman",
  "El Salvador": "El Salvador",
  "Elche": "Spanyol",
  "England": "Inggris",
  "Equatorial Guinea": "Equatorial Guinea",
  "Espanyol": "Spanyol",
  "Estonia": "Estonia",
  "Estoril": "Portugal",
  "Estudiantes de La Plata": "Argentina",
  "Ethiopia": "Etiopia",
  "Everton": "Inggris",
  "Excelsior": "Belanda",
  "Excelsior '31": "Belanda",
  "Excelsior Maassluis": "Belanda",
  "Exeter City": "Inggris",
  "F.C. København": "Denmark",
  "FC Augsburg": "Jerman",
  "FC Cologne": "Jerman",
  "FC Dallas": "Amerika Serikat",
  "FC Den Bosch": "Belanda",
  "FC Dordrecht": "Belanda",
  "FC Eindhoven": "Belanda",
  "FC Emmen": "Belanda",
  "FC Famalicao": "Inggris",
  "FC Groningen": "Belanda",
  "FC Juárez": "Meksiko",
  "FC Midtjylland": "Denmark",
  "FC Nordsjælland": "Denmark",
  "FC Porto": "Portugal",
  "FC Thun": "Swiss",
  "FC Tokyo": "Jepang",
  "FC Twente": "Belanda",
  "FC Utrecht": "Belanda",
  "FC Volendam": "Belanda",
  "Falkirk": "Skotlandia",
  "Faroe Islands": "Kepulauan Faroe",
  "Fenerbahce": "Turki",
  "Feyenoord Rotterdam": "Belanda",
  "Fiji": "Fiji",
  "Finland": "Finlandia",
  "Fiorentina": "Italia",
  "Flamengo": "Brasil",
  "Fluminense": "Brasil",
  "Fortuna Sittard": "Belanda",
  "France": "Prancis",
  "Frosinone": "Italia",
  "Fulham": "Inggris",
  "GVVV": "Belanda",
  "Gabon": "Gabon",
  "Galatasaray": "Turki",
  "Gamba Osaka": "Jepang",
  "Gambia": "Gambia",
  "Genoa": "Italia",
  "Georgia": "Georgia",
  "Germany": "Jerman",
  "Getafe": "Spanyol",
  "Ghana": "Ghana",
  "Gibraltar": "Gibraltar",
  "Gil Vicente": "Portugal",
  "Gillingham": "Inggris",
  "Girona": "Spanyol",
  "Go Ahead Eagles": "Belanda",
  "Granada": "Spanyol",
  "Greece": "Yunani",
  "Grenada": "Grenada",
  "Grimsby Town": "Inggris",
  "Grêmio": "Brasil",
  "Guabirá": "Bolivia",
  "Guadalajara": "Meksiko",
  "Guam": "Guam",
  "Guaraní": "Brasil",
  "Guatemala": "Guatemala",
  "Guinea": "Guinea",
  "Guyana": "Guyana",
  "Györi ETO FC": "Jerman",
  "HHC Hardenberg": "Belanda",
  "Haiti": "Haiti",
  "Hajduk Split": "Kroasia",
  "Hamburg SV": "Jerman",
  "Hapoel Be'er": "Spanyol",
  "Heart of Midlothian": "Skotlandia",
  "Heerenveen": "Belanda",
  "Helmond Sport": "Belanda",
  "Heracles Almelo": "Belanda",
  "Hibernian": "Skotlandia",
  "Honduras": "Honduras",
  "Hong Kong": "Hong Kong",
  "Houston Dynamo FC": "Amerika Serikat",
  "Huachipato": "Chili",
  "Huddersfield Town": "Inggris",
  "Hull City": "Inggris",
  "Hungary": "Hungaria",
  "IJsselmeervogels": "Belanda",
  "Iceland": "Islandia",
  "Independiente Medellín": "Kolombia",
  "Independiente Rivadavia": "Argentina",
  "Independiente Santa Fe": "Kolombia",
  "India": "India",
  "Indonesia": "Indonesia",
  "Inter Miami CF": "Amerika Serikat",
  "Internacional": "Brasil",
  "Internazionale": "Italia",
  "Ipswich Town": "Inggris",
  "Iran": "Iran",
  "Iraq": "Irak",
  "Israel": "Israel",
  "Istanbul Basaksehir": "Turki",
  "Italy": "Italia",
  "Ivory Coast": "Pantai Gading",
  "JEF United Ichihara-Chiba": "Jepang",
  "Jamaica": "Jamaika",
  "Japan": "Jepang",
  "Jordan": "Yordania",
  "Juventud": "Uruguay",
  "Juventus": "Italia",
  "KAA Gent": "Belgia",
  "KV Kortrijk": "Belgia",
  "KV Mechelen": "Belgia",
  "KVC Westerlo": "Belgia",
  "Kashima Antlers": "Jepang",
  "Kashiwa Reysol": "Jepang",
  "Kawasaki Frontale": "Jepang",
  "Kazakhstan": "Kazakhstan",
  "Kenya": "Kenya",
  "Kilmarnock": "Skotlandia",
  "Kloetinge": "Belanda",
  "Koninklijke HFC": "Belanda",
  "Konyaspor": "Turki",
  "Kozakken Boys": "Belanda",
  "Kuwait": "Kuwait",
  "Kyrgyz Republic": "Kyrgyz Republic",
  "LA Galaxy": "Amerika Serikat",
  "LAFC": "Amerika Serikat",
  "LASK Linz": "Austria",
  "Lanús": "Argentina",
  "Las Palmas": "Spanyol",
  "Latvia": "Latvia",
  "Lazio": "Italia",
  "Le Havre AC": "Prancis",
  "Le Mans": "Prancis",
  "Lebanon": "Lebanon",
  "Lecce": "Italia",
  "Lech Poznan": "Polandia",
  "Leeds United": "Inggris",
  "Leganés": "Spanyol",
  "Leicester City": "Inggris",
  "Lens": "Prancis",
  "Lesotho": "Lesotho",
  "Levante": "Spanyol",
  "Levski Sofia": "Bulgaria",
  "Leyton Orient": "Inggris",
  "León": "Meksiko",
  "Liberia": "Liberia",
  "Libertad": "Paraguay",
  "Libya": "Libya",
  "Liechtenstein": "Liechtenstein",
  "Liga de Quito": "Ekuador",
  "Lille": "Prancis",
  "Lincoln City": "Inggris",
  "Lithuania": "Lituania",
  "Liverpool": "Inggris",
  "Longa '30": "Belanda",
  "Lorient": "Prancis",
  "Luton Town": "Inggris",
  "Luxembourg": "Luksemburg",
  "Lyon": "Prancis",
  "MVV Maastricht": "Belanda",
  "Macará": "Ekuador",
  "Macau": "Macao",
  "Madagascar": "Madagascar",
  "Mainz": "Jerman",
  "Malawi": "Malawi",
  "Maldives": "Maldives",
  "Mali": "Mali",
  "Mallorca": "Spanyol",
  "Malta": "Malta",
  "Mamelodi Sundowns": "Afrika Selatan",
  "Manchester City": "Inggris",
  "Manchester United": "Inggris",
  "Mansfield Town": "Inggris",
  "Maritimo": "Portugal",
  "Marseille": "Prancis",
  "Martinique": "Martinique",
  "Mauritania": "Mauritania",
  "Mauritius": "Mauritius",
  "Melbourne City FC": "Australia",
  "Melbourne Victory": "Australia",
  "Metropolitanos": "Venezuela",
  "Mexico": "Meksiko",
  "Middlesbrough": "Inggris",
  "Millonarios": "Kolombia",
  "Millwall": "Inggris",
  "Milton Keynes Dons": "Inggris",
  "Minnesota United FC": "Amerika Serikat",
  "Mirassol": "Brasil",
  "Moldova": "Moldova",
  "Monagas SC": "Venezuela",
  "Mongolia": "Mongolia",
  "Montenegro": "Montenegro",
  "Monterrey": "Meksiko",
  "Montserrat": "Montserrat",
  "Monza": "Italia",
  "Moreirense": "Portugal",
  "Morocco": "Maroko",
  "Motherwell": "Skotlandia",
  "Mozambique": "Mozambique",
  "Myanmar": "Myanmar",
  "Málaga": "Spanyol",
  "NAC Breda": "Belanda",
  "NEC Nijmegen": "Belanda",
  "Nacional": "Uruguay",
  "Nacional Asunción": "Paraguay",
  "Nacional Potosí": "Bolivia",
  "Nagoya Grampus": "Jepang",
  "Namibia": "Namibia",
  "Napoli": "Italia",
  "Necaxa": "Meksiko",
  "Netherlands": "Belanda",
  "New Caledonia": "Kaledonia Baru",
  "New England Revolution": "Amerika Serikat",
  "New York City FC": "Amerika Serikat",
  "New Zealand": "Selandia Baru",
  "Newcastle Jets": "Australia",
  "Newcastle United": "Inggris",
  "Nicaragua": "Nicaragua",
  "Nice": "Prancis",
  "Niger": "Niger",
  "Nigeria": "Nigeria",
  "North Korea": "Korea DPR",
  "North Macedonia": "Makedonia Utara",
  "Northampton Town": "Inggris",
  "Northern Ireland": "Irlandia Utara",
  "Norway": "Norwegia",
  "Norwich City": "Inggris",
  "Nottingham Forest": "Inggris",
  "Notts County": "Inggris",
  "O'Higgins": "Chili",
  "OFI Crete": "Yunani",
  "OH Leuven": "Belgia",
  "Oldham Athletic": "Inggris",
  "Olympiacos": "Yunani",
  "Oman": "Oman",
  "Orlando City SC": "Amerika Serikat",
  "Orlando Pirates": "Afrika Selatan",
  "Osasuna": "Spanyol",
  "Oxford United": "Inggris",
  "PAOK": "Yunani",
  "PEC Zwolle": "Belanda",
  "PSV Eindhoven": "Belanda",
  "Pachuca": "Meksiko",
  "Pakistan": "Pakistan",
  "Palestine": "Palestina",
  "Palestino": "Chili",
  "Palmeiras": "Brasil",
  "Panama": "Panama",
  "Panathinaikos": "Yunani",
  "Papua New Guinea": "Papua Nugini",
  "Paraguay": "Paraguay",
  "Paris Saint-Germain": "Prancis",
  "Parma": "Italia",
  "Perth Glory": "Australia",
  "Peru": "Peru",
  "Peterborough United": "Inggris",
  "Peñarol": "Uruguay",
  "Philadelphia Union": "Amerika Serikat",
  "Philippines": "Filipina",
  "Plymouth Argyle": "Inggris",
  "Poland": "Polandia",
  "Port FC": "Thailand",
  "Port Vale": "Inggris",
  "Portland Timbers": "Amerika Serikat",
  "Portsmouth": "Inggris",
  "Portugal": "Portugal",
  "Preston North End": "Inggris",
  "Puebla": "Meksiko",
  "Puerto Rico": "Italia",
  "Pumas UNAM": "Meksiko",
  "Qatar": "Qatar",
  "Queens Park Rangers": "Inggris",
  "Querétaro": "Meksiko",
  "RB Leipzig": "Jerman",
  "RB Salzburg": "Austria",
  "RBC Roosendaal": "Belanda",
  "RKC Waalwijk": "Belanda",
  "RKVV Westlandia": "Belanda",
  "ROHDA Raalte": "Belanda",
  "Racing (Montevideo)": "Uruguay",
  "Racing Club": "Argentina",
  "Racing Genk": "Belgia",
  "Racing Santander": "Spanyol",
  "Rangers": "Skotlandia",
  "Rangers International": "Nigeria",
  "Rapid Vienna": "Austria",
  "Ratchaburi FC": "Thailand",
  "Rayo Vallecano": "Spanyol",
  "Reading": "Inggris",
  "Real Betis": "Spanyol",
  "Real Madrid": "Spanyol",
  "Real Oviedo": "Spanyol",
  "Real Salt Lake": "Amerika Serikat",
  "Real Sociedad": "Spanyol",
  "Real Valladolid": "Spanyol",
  "Red Bull Bragantino": "Brasil",
  "Red Bull New York": "Amerika Serikat",
  "Republic of Ireland": "Irlandia",
  "Rijnsburgse Boys": "Belanda",
  "Rio Ave": "Portugal",
  "River Plate": "Argentina",
  "Rivers United FC": "Nigeria",
  "Rochdale": "Inggris",
  "Roda JC Kerkrade": "Belanda",
  "Romania": "Rumania",
  "Rosario Central": "Argentina",
  "Rotherham United": "Inggris",
  "Royal Charleroi SC": "Belgia",
  "Russia": "Rusia",
  "Rwanda": "Rwanda",
  "SC Cambuur": "Belanda",
  "SC Freiburg": "Jerman",
  "SC Genemuiden": "Belanda",
  "SC Paderborn 07": "Jerman",
  "SC Rheindorf Altach": "Austria",
  "SK Sturm Graz": "Austria",
  "SV Elversberg": "Jerman",
  "SV Josko Ried": "Austria",
  "SV Venray": "Belanda",
  "Samsunspor": "Turki",
  "San Jose Earthquakes": "Amerika Serikat",
  "San Lorenzo": "Argentina",
  "San Marino": "San Marino",
  "Sanfrecce Hiroshima": "Jepang",
  "Santos": "Meksiko",
  "Sassuolo": "Italia",
  "Saudi Arabia": "Arab Saudi",
  "Schalke 04": "Jerman",
  "Scotland": "Skotlandia",
  "Seattle Sounders FC": "Amerika Serikat",
  "Senegal": "Senegal",
  "Serbia": "Serbia",
  "Sevilla": "Spanyol",
  "Seychelles": "Seychelles",
  "Shabab Al-Ahli": "Mesir",
  "Shakhtar Donetsk": "Ukraina",
  "Shamrock Rovers": "Irlandia",
  "Shanghai Port": "Spanyol",
  "Sheffield United": "Inggris",
  "Sheffield Wednesday": "Inggris",
  "Shimizu S-Pulse": "Jepang",
  "Shrewsbury Town": "Inggris",
  "Sierra Leone": "Sierra Leone",
  "Singapore": "Singapura",
  "Sint Maarten": "Sint Maarten",
  "Sint-Truidense": "Belgia",
  "Slovakia": "Slovakia",
  "Slovan Bratislava": "Slovakia",
  "Slovenia": "Slovenia",
  "Solomon Islands": "Solomon Islands",
  "South Africa": "Afrika Selatan",
  "South Korea": "Korea Selatan",
  "Southampton": "Inggris",
  "Spain": "Spanyol",
  "Sparta Nijkerk": "Belanda",
  "Sparta Prague": "Ceko",
  "Sparta Rotterdam": "Belanda",
  "Sporting CP": "Portugal",
  "Sporting Cristal": "Peru",
  "Sporting Gijón": "Spanyol",
  "Sporting Kansas City": "Amerika Serikat",
  "Sportivo Trinidense": "Paraguay",
  "Sri Lanka": "Sri Lanka",
  "St Johnstone": "Skotlandia",
  "St Mirren": "Skotlandia",
  "St. Gallen": "Swiss",
  "St. Kitts and Nevis": "St Kitts and Nevis",
  "St. Lucia": "St Lucia",
  "St. Vincent and the Grenadines": "St Vincent and Grenadines",
  "Stade Rennais": "Prancis",
  "Standard Liege": "Belgia",
  "Stevenage": "Inggris",
  "Stockport County": "Inggris",
  "Stoke City": "Inggris",
  "Strasbourg": "Prancis",
  "Sudan": "Sudan",
  "Sunderland": "Inggris",
  "Suriname": "Suriname",
  "Swansea City": "Inggris",
  "Sweden": "Swedia",
  "Swindon Town": "Inggris",
  "Switzerland": "Swiss",
  "Sydney FC": "Australia",
  "Syria": "Suriah",
  "São Paulo": "Brasil",
  "TOP Oss": "Belanda",
  "TP Mazembe": "Kongo DR",
  "TSG Hoffenheim": "Jerman",
  "TSV Hartberg": "Austria",
  "Tahiti": "Tahiti",
  "Tajikistan": "Tajikistan",
  "Tanzania": "Tanzania",
  "Telstar": "Belanda",
  "Tenerife": "Spanyol",
  "Thailand": "Thailand",
  "Tigre": "Argentina",
  "Tigres UANL": "Meksiko",
  "Tijuana": "Meksiko",
  "Togo": "Togo",
  "Toluca": "Meksiko",
  "Torino": "Italia",
  "Toronto FC": "Amerika Serikat",
  "Tottenham Hotspur": "Inggris",
  "Toulouse": "Prancis",
  "Trabzonspor": "Turki",
  "Tranmere Rovers": "Inggris",
  "Trinidad and Tobago": "Trinidad dan Tobago",
  "Troyes": "Prancis",
  "Tunisia": "Tunisia",
  "Turkmenistan": "Turkmenistan",
  "Turks and Caicos Islands": "Turks and Caicos Islands",
  "Türkiye": "Turki",
  "UCV FC": "Venezuela",
  "US Virgin Islands": "US Virgin Islands",
  "USV Hercules": "Belanda",
  "Udinese": "Italia",
  "Uganda": "Uganda",
  "Ukraine": "Ukraina",
  "United Arab Emirates": "Uni Emirat Arab",
  "United States": "Amerika Serikat",
  "Universidad Católica": "Chili",
  "Universidad de Chile": "Chili",
  "Universitario": "Peru",
  "Urawa Red Diamonds": "Jepang",
  "Uruguay": "Uruguay",
  "Uzbekistan": "Uzbekistan",
  "VV Katwijk": "Belanda",
  "VV Staphorst": "Belanda",
  "VVV-Venlo": "Belanda",
  "Valencia": "Spanyol",
  "Vancouver Whitecaps": "Amerika Serikat",
  "Vanuatu": "Vanuatu",
  "Vasco da Gama": "Brasil",
  "Venezuela": "Venezuela",
  "VfB Stuttgart": "Jerman",
  "Vietnam": "Vietnam",
  "Viktoria Plzen": "Ceko",
  "Villarreal": "Spanyol",
  "Vissel Kobe": "Jepang",
  "Vitesse": "Belanda",
  "Vitória": "Brasil",
  "Vitória de Guimaraes": "Portugal",
  "Waasland-Beveren": "Belgia",
  "Wales": "Wales",
  "Walsall": "Inggris",
  "Watford": "Inggris",
  "Wellington Phoenix FC": "Australia",
  "Werder Bremen": "Jerman",
  "West Bromwich Albion": "Inggris",
  "West Ham United": "Inggris",
  "Western Sydney Wanderers": "Australia",
  "Wigan Athletic": "Inggris",
  "Willem II": "Belanda",
  "Wolfsberger": "Austria",
  "Wolverhampton Wanderers": "Inggris",
  "Wrexham": "Inggris",
  "Wycombe Wanderers": "Inggris",
  "Yemen": "Yemen",
  "Yokohama F. Marinos": "Jepang",
  "York City": "Inggris",
  "Zambia": "Zambia",
  "Zulte-Waregem": "Belgia",
  "Zwaluwen '30": "Belanda",
};

/** Negara unik, urut abjad. */
export const COUNTRIES = ["Afghanistan", "Afrika Selatan", "Albania", "Aljazair", "American Samoa", "Amerika Serikat", "Andorra", "Angola", "Anguilla", "Antigua and Barbuda", "Arab Saudi", "Argentina", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belanda", "Belarus", "Belgia", "Belize", "Benin", "Bermuda", "Bolivia", "Bonaire", "Bosnia-Herzegovina", "Botswana", "Brasil", "British Virgin Islands", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cape Verde Islands", "Cayman Islands", "Ceko", "Chili", "China", "Comoros Islands", "Cook Islands", "Denmark", "Djibouti", "Dominica", "Ekuador", "El Salvador", "Equatorial Guinea", "Estonia", "Etiopia", "Fiji", "Filipina", "Finlandia", "Gabon", "Gambia", "Georgia", "Ghana", "Gibraltar", "Grenada", "Guam", "Guatemala", "Guinea", "Guyana", "Haiti", "Honduras", "Hong Kong", "Hungaria", "India", "Indonesia", "Inggris", "Irak", "Iran", "Irlandia", "Irlandia Utara", "Islandia", "Israel", "Italia", "Jamaika", "Jepang", "Jerman", "Kaledonia Baru", "Kamerun", "Kanada", "Kazakhstan", "Kenya", "Kepulauan Faroe", "Kolombia", "Kongo DR", "Korea DPR", "Korea Selatan", "Kosta Rika", "Kroasia", "Kuba", "Kuwait", "Kyrgyz Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lituania", "Luksemburg", "Macao", "Madagascar", "Makedonia Utara", "Malawi", "Maldives", "Mali", "Malta", "Maroko", "Martinique", "Mauritania", "Mauritius", "Meksiko", "Mesir", "Moldova", "Mongolia", "Montenegro", "Montserrat", "Mozambique", "Myanmar", "Namibia", "Nicaragua", "Niger", "Nigeria", "Norwegia", "Oman", "Pakistan", "Palestina", "Panama", "Pantai Gading", "Papua Nugini", "Paraguay", "Peru", "Polandia", "Portugal", "Prancis", "Qatar", "Republik Dominika", "Rumania", "Rusia", "Rwanda", "San Marino", "Selandia Baru", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapura", "Sint Maarten", "Siprus", "Skotlandia", "Slovakia", "Slovenia", "Solomon Islands", "Spanyol", "Sri Lanka", "St Kitts and Nevis", "St Lucia", "St Vincent and Grenadines", "Sudan", "Suriah", "Suriname", "Swedia", "Swiss", "Tahiti", "Tajikistan", "Tanzania", "Thailand", "Togo", "Trinidad dan Tobago", "Tunisia", "Turki", "Turkmenistan", "Turks and Caicos Islands", "US Virgin Islands", "Uganda", "Ukraina", "Uni Emirat Arab", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Wales", "Yemen", "Yordania", "Yunani", "Zambia"];
